name: Android GMD CI

on: [push]

jobs:

  android-ci:
    runs-on: macos-latest

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

