name: Android GMD CI

on: [push]

jobs:

  android-ci:
    runs-on: macos-latest

    steps:
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: actions/checkout@v2

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Run instrumented tests with GMD
      run: ./gradlew pixel4Api30DemoDebugAndroidTest -Dorg.gradle.workers.max=1 -Pandroid.tenageddevices.emulator.gpu="swiftshader_indirect"
