name: Android GMD CI

on: [push]

jobs:

  android-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: "Android CI Github Action"
      uses: docker-android-sdk/android-30@master
      with:
        args: |
          ./gradlew assembleDebug
